// Generated by tools/prepare_parser_probe.py; build-specific experimental guards.
struct Guard { uint64_t address; size_t size; const char* sha256; };
static const Guard guards[] = {
    {0x10057d5f8ULL, 6080, "412d4095c11a6071a025f88728d0c568b42010c9cd1161e42b500c5b044cee01"},
    {0x10057d2dcULL, 136, "7a84d9c17e7fc4abb7ef4549098cc6c7746d081484d395c17e31519276f66cbf"},
    {0x10057c26cULL, 408, "eb2bb01461e2c57d8595e401176ac700bb3342d7966e3d4541a5640e21daabdb"},
    {0x1005b25acULL, 80, "1678dad75c722cb4a44d4b6ff9aa8ee3eeeed8fd160b6423f4240775fc9c79f9"},
    {0x1005b25fcULL, 2204, "eb890c5b22c5f2c23306e3f9f6e4d76b64085fc65b4baea80f872fdf6678c4f5"},
    {0x100747a50ULL, 356, "7a2fbfbbea95fe650e5c456bec4055ff01b7062e1c5e90c5e1d7c65aba4c0eea"},
};
static const uint64_t kParser = 0x10057d5f8ULL, kVtable = 0x1040037b8ULL, kDelete = 0x1005b25acULL;
static const char* kUUID = "46743daaff0430269dab1cc69450155a";
