#!/usr/bin/env python3
"""Generate the clickthrough-probe deck skins from one template.

R2 wants "otherwise identical minimal deck skins": one attribute differs
between variants and nothing else, so the skins are generated rather than
hand-edited. The overlap test is two buttons at the same coordinates, the
lower one declared first; each writes a different global, so HTTP can read
back which one received the click without judging a screenshot.

    python3 tests/Skins/clickthrough-probe/generate.py            # write the repo copies
    python3 tests/Skins/clickthrough-probe/generate.py --install  # + install to VirtualDJ
"""

from __future__ import annotations

import argparse
import shutil
import struct
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
INSTALL = Path.home() / "Library/Application Support/VirtualDJ/Skins"
PREFIX = "ZZ Clickthrough"

# (variant, extra attribute on the TOP button, what it tests)
VARIANTS = [
    ("baseline", "", "no extra attribute: the top button should swallow the click"),
    ("visible-off", "visibility=\"param_equal 'no' 'yes'\"",
     "calibration with a known working attribute: the top button must not render, "
     "so the click must reach the bottom button"),
    ("pass", 'clickthrough="pass"',
     "the candidate: the value the base reader compares against"),
    ("value-control", 'clickthrough="qzqzqz"',
     "nonsense VALUE on the real attribute"),
    ("attr-control", 'zzclickthrough="pass"',
     "nonsense ATTRIBUTE carrying the real value"),
    # The boolean path. Named disassembly of CXMLNode::getBoolParam on builds
    # 9.0.5308, 9.0.7607 and 18.0.9246 accepts exactly yes/true/no/false,
    # case-insensitively, and returns the caller's default (false here) for
    # anything else — so `no`, `1`, `0` collapse onto value-control, and the
    # only unobserved stored state is the boolean TRUE.
    ("yes", 'clickthrough="yes"',
     "boolean TRUE via the generic parser: the one stored state never observed"),
    ("true", 'clickthrough="TRUE"',
     "boolean TRUE in the other accepted spelling, upper-cased to exercise the "
     "case-insensitive compare; must agree with `yes`"),
]

# Second series (2026-09-07): the attribute on a CONTAINER rather than the
# button, and pass-through across more than one layer. The TOP button carries
# nothing; a wrapper around it carries the candidate. Three wrapper kinds,
# because the historical `CSkinPanel::loadChildren` disassembly takes a
# different construction path for a `<group>` with no visibility/novisibility
# attribute than for one that has either, or for a `<panel>`.
#   (variant, wrapper kind, attribute on the wrapper, why)
WRAPPERS = {
    "panel": ("<panel {attr}>", "</panel>"),
    "group": ("<group {attr}>", "</group>"),
    # constant-true visibility so the wrapper is drawn but takes the factory path
    "group-vis": ("<group visibility=\"param_equal 'yes' 'yes'\" {attr}>", "</group>"),
}
WRAPPED = [
    (kind + ("-" + tag if tag else "-none"), kind, attr,
     f"{kind} wrapper around the top button carrying {attr or 'no attribute'}")
    for kind in WRAPPERS
    for tag, attr in (("", ""), ("pass", 'clickthrough="pass"'), ("yes", 'clickthrough="yes"'))
]

# Three layers: BOTTOM, MIDDLE, TOP all on the same rectangle, each with its own
# global. Does `pass` on the top layer reach only the next one down, or all?
#   (variant, attribute on TOP, attribute on MIDDLE, why)
LAYERED = [
    ("3-top-pass", 'clickthrough="pass"', "",
     "three layers, pass on TOP only: does the click stop at MIDDLE?"),
    ("3-both-pass", 'clickthrough="pass"', 'clickthrough="pass"',
     "three layers, pass on TOP and MIDDLE: does it reach BOTTOM?"),
    ("3-top-yes", 'clickthrough="yes"', "",
     "three layers, boolean on TOP only: transparent to MIDDLE, which swallows?"),
]

TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!-- clickthrough probe: {why}
     Generated by tests/Skins/clickthrough-probe/generate.py — do not hand-edit. -->
<skin name="{name}" version="8" width="900" height="560" author="virtualdj-api-reference">

  <font name="Helvetica Neue"/>
  <nbdecks value="2"/>

  <panel name="main" visible="yes">
    <square color="#11151A">
      <pos x="0" y="0"/>
      <size width="900" height="560"/>
    </square>
    <grabzone x="0" y="0" width="900" height="40"/>

    <textzone>
      <pos x="24" y="12"/>
      <size width="852" height="20"/>
      <text font="arial" size="14" weight="bold" color="#E7EEF7" align="left" format="{name}"/>
    </textzone>

    <!-- Marker: proves the skin rendered at all. -->
    <textzone>
      <pos x="24" y="40"/>
      <size width="852" height="18"/>
      <text font="arial" size="12" color="#93A1B1" align="left" format="marker: skin rendered"/>
    </textzone>

    <!-- BOTTOM button, declared first. -->
    <button action="set '$ct_bottom' 1">
      <pos x="{bx}" y="{by}"/>
      <size width="{bw}" height="{bh}"/>
      <off shape="square" color="#1D4F2A" border="#3FBF63" border_size="3"/>
      <on shape="square" color="#3FBF63" border="#3FBF63" border_size="3"/>
      <text font="arial" size="16" weight="bold" color="#E7EEF7" align="center" format="BOTTOM"/>
    </button>

{middle}    <!-- TOP button, declared last, exactly over the others. -->
    {open_wrap}
    <button action="set '$ct_top' 1" {extra}>
      <pos x="{bx}" y="{by}"/>
      <size width="{bw}" height="{bh}"/>
      <off shape="square" color="#4A2350" border="#C46BD8" border_size="3"/>
      <on shape="square" color="#C46BD8" border="#C46BD8" border_size="3"/>
      <text font="arial" size="16" weight="bold" color="#E7EEF7" align="center" format="TOP"/>
    </button>
    {close_wrap}

    <!-- Readback, so the window itself shows what HTTP reads. -->
    <textzone>
      <pos x="24" y="{ry}"/>
      <size width="852" height="18"/>
      <text font="arial" size="12" color="#63D2FF" align="left" format="top=`get_var '$ct_top'` mid=`get_var '$ct_mid'` bottom=`get_var '$ct_bottom'`"/>
    </textzone>
  </panel>

  <deck deck="1">
    <textzone>
      <pos x="24" y="{dy}"/>
      <size width="400" height="18"/>
      <text font="arial" size="12" color="#93A1B1" align="left" format="deck 1 bpm `get_bpm`"/>
    </textzone>
  </deck>

  <deck deck="2">
    <textzone>
      <pos x="460" y="{dy}"/>
      <size width="400" height="18"/>
      <text font="arial" size="12" color="#93A1B1" align="left" format="deck 2 bpm `get_bpm`"/>
    </textzone>
  </deck>

</skin>
"""

GEOMETRY = dict(bx=300, by=180, bw=300, bh=160, ry=380, dy=420)


def png(width: int, height: int, rgb: tuple[int, int, int]) -> bytes:
    """A flat-colour PNG.

    VirtualDJ refuses a skin folder with no image next to the XML — it puts up
    "Impossible to open skin <name>" and keeps the current skin — so every
    installed probe needs a `skin.png` and a `preview.png` even though neither
    is referenced from the XML.
    """
    row = bytes(rgb) * width
    raw = b"".join(b"\x00" + row for _ in range(height))

    def chunk(tag: bytes, body: bytes) -> bytes:
        return (struct.pack(">I", len(body)) + tag + body
                + struct.pack(">I", zlib.crc32(tag + body) & 0xFFFFFFFF))

    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9))
            + chunk(b"IEND", b""))


MIDDLE = """    <!-- MIDDLE button, declared second, same rectangle. -->
    <button action="set '$ct_mid' 1" {mid_extra}>
      <pos x="{bx}" y="{by}"/>
      <size width="{bw}" height="{bh}"/>
      <off shape="square" color="#4F3D1D" border="#D8A83F" border_size="3"/>
      <on shape="square" color="#D8A83F" border="#D8A83F" border_size="3"/>
      <text font="arial" size="16" weight="bold" color="#E7EEF7" align="center" format="MIDDLE"/>
    </button>

"""


def render(variant: str, extra: str, why: str, *, wrapper: str = "",
           wrapper_attr: str = "", mid_extra: str | None = None) -> tuple[str, str]:
    name = f"{PREFIX} {variant}"
    open_wrap = close_wrap = ""
    if wrapper:
        open_wrap, close_wrap = WRAPPERS[wrapper]
        open_wrap = open_wrap.format(attr=wrapper_attr).replace(" >", ">")
    middle = MIDDLE.format(mid_extra=mid_extra, **GEOMETRY) if mid_extra is not None else ""
    xml = TEMPLATE.format(name=name, extra=extra, why=why, open_wrap=open_wrap,
                          close_wrap=close_wrap, middle=middle, **GEOMETRY)
    # An empty wrapper or middle slot leaves an indented blank line behind.
    return name, "\n".join(line.rstrip() for line in xml.splitlines()) + "\n"


def all_variants():
    """Every (variant, render kwargs) pair, first series then the two second-series groups."""
    for variant, extra, why in VARIANTS:
        yield variant, dict(extra=extra, why=why)
    for variant, kind, attr, why in WRAPPED:
        yield variant, dict(extra="", why=why, wrapper=kind, wrapper_attr=attr)
    for variant, top, mid, why in LAYERED:
        yield variant, dict(extra=top, why=why, mid_extra=mid)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--install", action="store_true",
                    help=f"also copy each skin into {INSTALL}")
    ap.add_argument("--uninstall", action="store_true",
                    help="remove the installed copies and stop")
    args = ap.parse_args()

    if args.uninstall:
        for path in sorted(INSTALL.glob(f"{PREFIX} *")):
            shutil.rmtree(path)
            print(f"removed {path}")
        return 0

    for variant, kwargs in all_variants():
        name, xml = render(variant, **kwargs)
        out = HERE / f"{variant}.xml"
        out.write_text(xml, encoding="utf-8")
        print(f"wrote {out.relative_to(HERE.parents[2])}")
        if args.install:
            folder = INSTALL / name
            folder.mkdir(parents=True, exist_ok=True)
            (folder / "skin.xml").write_text(xml, encoding="utf-8")
            (folder / "skin.png").write_bytes(png(64, 64, (0x11, 0x15, 0x1A)))
            (folder / "preview.png").write_bytes(png(64, 40, (0x11, 0x15, 0x1A)))
            print(f"  installed {folder}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
