#!/usr/bin/env python3
"""Generate an element/attribute inventory of the in-repo XML corpora.

Scans skins, pads, samplerbanks, and mapper XML with a tolerant tokenizer
(built-in skin XML is not strict XML: raw `&`, `&&`, and `>` appear inside
quoted attribute values), cross-checks element names against the reference
docs, and writes `Reference/Skin XML Inventory.md`.

Usage:
    python3 tools/extract_xml_inventory.py           # (re)write the report
    python3 tools/extract_xml_inventory.py --check   # fail on new undocumented elements
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Reference" / "Skin XML Inventory.md"

GENERATED_HEADER = (
    "<!-- GENERATED by tools/extract_xml_inventory.py — do not hand-edit. "
    "Regenerate with `just inventory`. -->"
)

# family name -> (glob patterns, reference docs to cross-check)
FAMILIES: list[tuple[str, list[str], list[str]]] = [
    (
        "skins",
        [
            "Skins/Built-In/**/*.xml",
            "Skins/SDK Example - Custom Browser Skin/skin.xml",
            "Skins/ModularSkeleton/build/*.xml",
            "Skins/GraveRaver/build/*.xml",
        ],
        ["Reference/Skin SDK.md", "Reference/Skin Waveforms.md"],
    ),
    (
        "pads",
        ["Pads/**/*.xml", "Test/**/*.xml"],
        ["Reference/Pad Page XML.md", "Reference/Example Pad XML Pages.md"],
    ),
    (
        "samplerbanks",
        ["Samplerbanks/**/*.xml"],
        [],
    ),
    (
        "mappers",
        ["Mappers/**/*.xml"],
        ["Reference/Mapper XML.md"],
    ),
]

NAME_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_.:-]*")


@dataclass
class ElementStats:
    uses: int = 0
    files: set[str] = field(default_factory=set)
    attributes: Counter = field(default_factory=Counter)


def scan_tags(text: str) -> list[tuple[str, list[str]]]:
    """Tolerantly tokenize open tags: returns (element, [attribute names]).

    Quote-aware so `>` / `<` / raw `&` inside quoted attribute values (VDJScript
    ternaries etc.) do not break tag detection. Skips comments, CDATA, prolog,
    doctype, and closing tags.
    """
    tags: list[tuple[str, list[str]]] = []
    i = 0
    n = len(text)
    while True:
        i = text.find("<", i)
        if i == -1:
            break
        if text.startswith("<!--", i):
            end = text.find("-->", i + 4)
            i = n if end == -1 else end + 3
            continue
        if text.startswith("<![CDATA[", i):
            end = text.find("]]>", i + 9)
            i = n if end == -1 else end + 3
            continue
        if text.startswith("<?", i) or text.startswith("<!", i):
            end = text.find(">", i)
            i = n if end == -1 else end + 1
            continue
        if text.startswith("</", i):
            end = text.find(">", i)
            i = n if end == -1 else end + 1
            continue
        match = NAME_RE.match(text, i + 1)
        if not match:
            i += 1
            continue
        name = match.group(0).lower()
        k = match.end()
        attrs: list[str] = []
        while k < n:
            c = text[k]
            if c == ">":
                k += 1
                break
            if c in " \t\r\n/":
                k += 1
                continue
            attr_match = NAME_RE.match(text, k)
            if not attr_match:
                k += 1
                continue
            attrs.append(attr_match.group(0).lower())
            k = attr_match.end()
            while k < n and text[k] in " \t\r\n":
                k += 1
            if k < n and text[k] == "=":
                k += 1
                while k < n and text[k] in " \t\r\n":
                    k += 1
                if k < n and text[k] in "\"'":
                    quote = text[k]
                    end = text.find(quote, k + 1)
                    k = n if end == -1 else end + 1
                else:
                    while k < n and text[k] not in " \t\r\n>":
                        k += 1
        tags.append((name, attrs))
        i = k
    return tags


def collect_family(patterns: list[str]) -> tuple[dict[str, ElementStats], list[Path]]:
    files: list[Path] = []
    seen: set[Path] = set()
    for pattern in patterns:
        for path in sorted(ROOT.glob(pattern)):
            if path.is_file() and path not in seen:
                seen.add(path)
                files.append(path)
    stats: dict[str, ElementStats] = {}
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        rel = str(path.relative_to(ROOT))
        for name, attrs in scan_tags(text):
            entry = stats.setdefault(name, ElementStats())
            entry.uses += 1
            entry.files.add(rel)
            entry.attributes.update(attrs)
    return stats, files


def load_doc_texts(doc_paths: list[str]) -> tuple[str, str, list[tuple[str, bool]]]:
    """Return (full doc text, fenced-code-block text, per-doc availability)."""
    combined: list[str] = []
    availability: list[tuple[str, bool]] = []
    for rel in doc_paths:
        path = ROOT / rel
        exists = path.is_file()
        availability.append((rel, exists))
        if exists:
            combined.append(path.read_text(encoding="utf-8"))
    text = "\n".join(combined)
    fenced = "\n".join(re.findall(r"^```[^\n]*\n(.*?)^```", text, re.MULTILINE | re.DOTALL))
    return text, fenced, availability


def is_documented(name: str, doc_text: str, fenced_text: str) -> bool:
    """Documented = backticked `<name>` mention (headings included) or a
    `<name ...>` tag inside a fenced code block."""
    if not doc_text:
        return False
    escaped = re.escape(name)
    if re.search(r"`</?" + escaped + r"[\s/>`]", doc_text, re.IGNORECASE):
        return True
    return bool(re.search(r"</?" + escaped + r"[\s/>]", fenced_text, re.IGNORECASE))


def format_attributes(attributes: Counter) -> str:
    if not attributes:
        return "—"
    parts = [
        f"`{attr}` ({count})"
        for attr, count in sorted(attributes.items(), key=lambda kv: (-kv[1], kv[0]))
    ]
    return ", ".join(parts)


def build_report() -> tuple[str, dict[str, list[str]]]:
    lines: list[str] = []
    undocumented: dict[str, list[str]] = {}
    family_sections: list[str] = []
    summary_lines: list[str] = []
    total_elements = 0
    total_undocumented = 0

    for family, patterns, doc_paths in FAMILIES:
        stats, files = collect_family(patterns)
        doc_text, fenced_text, availability = load_doc_texts(doc_paths)
        ordered = sorted(stats.items(), key=lambda kv: (-kv[1].uses, kv[0]))

        family_undocumented: list[str] = []
        rows: list[str] = []
        for name, entry in ordered:
            if doc_paths:
                documented = is_documented(name, doc_text, fenced_text)
                doc_cell = "yes" if documented else "**no**"
                if not documented:
                    family_undocumented.append(name)
            else:
                doc_cell = "n/a"
            rows.append(
                f"| `<{name}>` | {entry.uses} | {len(entry.files)} | {doc_cell} "
                f"| {format_attributes(entry.attributes)} |"
            )

        undocumented[family] = family_undocumented
        total_elements += len(ordered)
        total_undocumented += len(family_undocumented)

        doc_notes = []
        for rel, exists in availability:
            doc_notes.append(f"`{rel}`" + ("" if exists else " (missing, treated as empty)"))
        docs_line = ", ".join(doc_notes) if doc_notes else "none (no reference doc for this family yet)"

        section: list[str] = []
        section.append(f"## {family.capitalize()}")
        section.append("")
        section.append(
            f"{len(files)} files scanned, {len(ordered)} distinct elements. "
            f"Docs cross-checked: {docs_line}."
        )
        section.append("")
        section.append("| Element | Uses | Files | Documented | Attributes (count) |")
        section.append("| --- | ---: | ---: | --- | --- |")
        section.extend(rows)
        section.append("")
        family_sections.append("\n".join(section))

        if doc_paths:
            listed = ", ".join(f"`<{n}>`" for n in family_undocumented) or "none"
            summary_lines.append(
                f"- {family}: {len(ordered)} elements, "
                f"{len(family_undocumented)} undocumented ({listed})"
            )
        else:
            summary_lines.append(
                f"- {family}: {len(ordered)} elements, no reference doc to check against"
            )

    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("# Skin XML Inventory")
    lines.append("")
    lines.append(
        "Element and attribute inventory of every offline XML corpus in this repo, "
        "cross-checked against the reference docs. Built-in skin XML is not strict "
        "XML (raw `&`, `&&`, and `>` inside quoted attribute values), so this report "
        "is produced by a tolerant quote-aware tokenizer, not an XML parser."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(
        f"{total_elements} distinct elements observed across all families; "
        f"{total_undocumented} undocumented."
    )
    lines.append("")
    lines.extend(summary_lines)
    lines.append("")
    for family, names in undocumented.items():
        lines.append(f"<!-- undocumented {family}: {','.join(names)} -->")
    lines.append("")
    lines.extend(family_sections)
    return "\n".join(lines).rstrip() + "\n", undocumented


def parse_committed_undocumented(text: str) -> dict[str, set[str]]:
    committed: dict[str, set[str]] = {}
    for match in re.finditer(r"<!-- undocumented (\w+): ([^>]*?) -->", text):
        names = {n for n in match.group(2).split(",") if n}
        committed[match.group(1)] = names
    return committed


def run_check(report: str, undocumented: dict[str, list[str]]) -> int:
    if not OUTPUT.is_file():
        OUTPUT.write_text(report, encoding="utf-8")
        print(f"{OUTPUT.relative_to(ROOT)}: did not exist, wrote initial report")
        return 0
    committed = parse_committed_undocumented(OUTPUT.read_text(encoding="utf-8"))
    failures: list[str] = []
    for family, names in undocumented.items():
        new = sorted(set(names) - committed.get(family, set()))
        if new:
            failures.append(f"{family}: new undocumented elements: {', '.join(new)}")
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        print(
            "Document the elements or regenerate the report with "
            "`python3 tools/extract_xml_inventory.py`.",
            file=sys.stderr,
        )
        return 1
    print("XML inventory check passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit nonzero if a new undocumented element appears vs the committed report",
    )
    args = parser.parse_args()

    report, undocumented = build_report()
    if args.check:
        return run_check(report, undocumented)

    OUTPUT.write_text(report, encoding="utf-8")
    total = sum(len(names) for names in undocumented.values())
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({total} undocumented elements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
