#!/usr/bin/env python3
"""Freeze build-9644 arm64 parser boundaries and code fingerprints for a bounded experiment."""
import hashlib,json,sys
from pathlib import Path
from types import SimpleNamespace
from extract_verb_table import BINARY,sections,slice_offset
from extract_skin_classes import function_starts
from extract_action_contracts import rtti_graph
from plugin_memory import verify


def prepare():
    capture=json.loads(Path('tests/plugin-memory-9644.json').read_text())
    binary=Path(BINARY); verification=verify(capture,binary)
    raw=binary.read_bytes();base=slice_offset(raw)
    if hashlib.sha256(raw).hexdigest()!=verification['binary_sha256']:raise ValueError('binary changed')
    if capture['build']!='18.0.9644':raise ValueError('this experiment is build-specific')
    text=next(s for s in sections(raw,base) if s[1]=='__text')
    starts=function_starts(SimpleNamespace(data=raw,base=base));ends=dict(zip(starts,starts[1:]))
    graph=rtti_graph(raw,prefixes=('ACTION_is_using',))['ACTION_is_using']
    targets={'create_candidate':0x10057d5f8,'parameter_reader':0x10057d2dc,'base_destructor':0x10057c26c,
             'delete_destructor':graph['slots'][1],'consumer':graph['slots'][3],
             'GetInfo':int(capture['callback_slots'][1]['unslid_address'],16)}
    routines={}
    for name,a in targets.items():
        off=base+text[4]+a-text[2];body=raw[off:off+ends[a]-a]
        routines[name]={'start':hex(a),'end':hex(ends[a]),'sha256':hashlib.sha256(body).hexdigest()}
    result={'build':capture['build'],'arch':'arm64','image_uuid':capture['image_uuid'],
            'binary_sha256':verification['binary_sha256'],'evidence_tier':2,'routines':routines,
            'expected_vtable':hex(graph['vtable']),
            'layout_leads':{'refcount_offset':8,'parameter_begin_offset':32,'parameter_end_offset':40,'parameter_capacity_offset':48,'parameter_stride':40},
            'scope':'Fixed is_using scripts only; candidate ABI void*(const char*,const char**,int) inferred from current SDK callbacks and historical named signature. Not a supported API.'}
    header='// Generated by tools/prepare_parser_probe.py; build-specific experimental guards.\n'
    header+='struct Guard { uint64_t address; size_t size; const char* sha256; };\nstatic const Guard guards[] = {\n'
    for r in routines.values():header+=f'    {{{r["start"]}ULL, {int(r["end"],16)-int(r["start"],16)}, "{r["sha256"]}"}},\n'
    header+='};\n'
    header+=f'static const uint64_t kParser = {targets["create_candidate"]:#x}ULL, kVtable = {graph["vtable"]:#x}ULL, kDelete = {graph["slots"][1]:#x}ULL;\n'
    header+=f'static const char* kUUID = "{capture["image_uuid"]}";\n'
    return result,header

if __name__=='__main__':
    result,header=prepare()
    if '--check' in sys.argv:
        assert json.loads(Path('tests/parser-object-layout-9644.json').read_text())==result
        assert Path('tools/plugin/parser_guard_9644.h').read_text()==header
        print('parser fingerprints reproduce')
    else:
        Path('tests/parser-object-layout-9644.json').write_text(json.dumps(result,indent=2)+'\n')
        Path('tools/plugin/parser_guard_9644.h').write_text(header)
